/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-30 06:29:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ContentLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1637281236679L));
    _jspx_dependants.put("jar:file:/C:/springCoding/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/msixpet/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506773284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>");
      if (_jspx_meth_tiles_005fgetAsString_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Preloader -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/include/dist2/css/preloader.css\" type=\"text/css\" media=\"screen, print\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/include/dist2/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/include/dist2/css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/include/dist2/css/dist/owl.theme.default.css\">\r\n");
      out.write("    <!-- Animate CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/include/dist2/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"/resources/include/dist2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Style -->\r\n");
      out.write("    <link href=\"/resources/include/dist2/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Responsive CSS -->\r\n");
      out.write("    <link href=\"/resources/include/dist2/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"js/lte-ie7.js\"></script>\r\n");
      out.write("	  <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("	  <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("	<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("                <!-- Preloader -->\r\n");
      out.write("                <div id=\"preloader\">\r\n");
      out.write("                    <div id=\"status\">&nbsp;</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header id=\"HOME\" style=\"background-position: 50% -125px;\">\r\n");
      out.write("	        <div class=\"section_overlay\">\r\n");
      out.write("	            <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("	             ");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("</nav> \r\n");
      out.write("	        </div>          \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"services\" id=\"SERVICE\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 text-center\">\r\n");
      out.write("                    <div class=\"single_service wow fadeInUp\" data-wow-delay=\"1s\">\r\n");
      out.write("                        <i class=\"icon-pencil\"></i>\r\n");
      out.write("                        <h2>Design</h2>\r\n");
      out.write("                        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 text-center\">\r\n");
      out.write("                    <div class=\"single_service wow fadeInUp\" data-wow-delay=\"2s\">\r\n");
      out.write("                        <i class=\"icon-gears\"></i>\r\n");
      out.write("                        <h2>Development</h2>\r\n");
      out.write("                        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 text-center\">\r\n");
      out.write("                    <div class=\"single_service wow fadeInUp\" data-wow-delay=\"3s\">\r\n");
      out.write("                        <i class=\"icon-camera\"></i>\r\n");
      out.write("                        <h2>Photography</h2>\r\n");
      out.write("                        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 text-center\">\r\n");
      out.write("                    <div class=\"single_service wow fadeInUp\" data-wow-delay=\"4s\">\r\n");
      out.write("                        <i class=\"icon-magnifying-glass\"></i>\r\n");
      out.write("                        <h2>Seo</h2>\r\n");
      out.write("                        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"about_us_area\" id=\"ABOUT\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 text-center\">\r\n");
      out.write("                    <div class=\"about_title\">\r\n");
      out.write("                        <h2>About Me</h2>\r\n");
      out.write("                        <img src=\"/resources/include/dist2/images/shape.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4  wow fadeInLeft animated\">\r\n");
      out.write("                    <div class=\"single_progress_bar\">\r\n");
      out.write("                        <h2>DESIGN - 90%</h2>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                          <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 90%;\">\r\n");
      out.write("                            <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single_progress_bar\">\r\n");
      out.write("                        <h2>DEVELOPMENT - 60%</h2>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                          <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%;\">\r\n");
      out.write("                            <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single_progress_bar\">\r\n");
      out.write("                        <h2>MARKETING - 75%</h2>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                          <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 75%;\">\r\n");
      out.write("                            <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single_progress_bar\">\r\n");
      out.write("                        <h2>SEO - 95%</h2>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                          <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 95%;\">\r\n");
      out.write("                            <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4  wow fadeInRight animated\">\r\n");
      out.write("                    <p class=\"about_us_p\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed quia non numquam eius modi tempora.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4  wow fadeInRight animated\">\r\n");
      out.write("                    <p class=\"about_us_p\">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <section class=\"testimonial text-center wow fadeInUp animated\" id=\"TESTIMONIAL\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"icon\">\r\n");
      out.write("                <i class=\"icon-quote\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"owl-carousel\">\r\n");
      out.write("                <div class=\"single_testimonial text-center wow fadeInUp animated\">\r\n");
      out.write("                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores<br/> eos qui ratione voluptatem sequi nesciunt.</p>\r\n");
      out.write("                    <h4>-JOHN DOE</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single_testimonial text-center\">\r\n");
      out.write("                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius<br/> modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>\r\n");
      out.write("                    <h4>-JOHN SMITH</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fun_facts\">\r\n");
      out.write("    	<section class=\"header parallax home-parallax page\" id=\"fun_facts\" style=\"background-position: 50% -150px;\">\r\n");
      out.write("	        <div class=\"section_overlay\">\r\n");
      out.write("	            <div class=\"container\">\r\n");
      out.write("	                <div class=\"row\">\r\n");
      out.write("	                    <div class=\"col-md-6 wow fadeInLeft animated\">\r\n");
      out.write("	                        <div class=\"row\">\r\n");
      out.write("	                            <div class=\"col-md-4\">\r\n");
      out.write("	                                <div class=\"single_count\">\r\n");
      out.write("	                                    <i class=\"icon-toolbox\"></i>\r\n");
      out.write("	                                    <h3>300</h3>\r\n");
      out.write("	                                    <p>Project Done</p>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <div class=\"col-md-4\">\r\n");
      out.write("	                                <div class=\"single_count\">\r\n");
      out.write("	                                    <i class=\"icon-clock\"></i>\r\n");
      out.write("	                                    <h3>1700+</h3>\r\n");
      out.write("	                                    <p>Hours Worked</p>\r\n");
      out.write("	                                </div>                            \r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <div class=\"col-md-4\">\r\n");
      out.write("	                                <div class=\"single_count\">\r\n");
      out.write("	                                    <i class=\"icon-trophy\"></i>\r\n");
      out.write("	                                    <h3>37</h3>\r\n");
      out.write("	                                    <p>Awards Won</p>\r\n");
      out.write("	                                </div>                            \r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"col-md-5 col-md-offset-1 wow fadeInRight animated\">\r\n");
      out.write("	                        <div class=\"imac\">\r\n");
      out.write("	                            <img src=\"/resources/include/dist2/images/imac.png\" alt=\"\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>            \r\n");
      out.write("	        </div>\r\n");
      out.write("	    </section>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"work_area\" id=\"WORK\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 text-center\">\r\n");
      out.write("                    <div class=\"work_title  wow fadeInUp animated\">\r\n");
      out.write("                        <h1>Latest Works</h1>\r\n");
      out.write("                        <img src=\"/resources/include/dist2/images/shape.png\" alt=\"\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna <br> aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 text-center\">\r\n");
      out.write("                    <div class=\"footer_logo   wow fadeInUp animated\">\r\n");
      out.write("                        <img src=\"/resources/include/dist2/images/logo.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 text-center   wow fadeInUp animated\">\r\n");
      out.write("                    <div class=\"social\">\r\n");
      out.write("                        <h2>Follow Me on Here</h2>\r\n");
      out.write("                        <ul class=\"icon_list\">\r\n");
      out.write("                            <li><a href=\"http://www.facebook.com/abdullah.noman99\"target=\"_blank\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"http://www.twitter.com/absconderm\"target=\"_blank\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"http://www.dribbble.com/abdullahnoman\"target=\"_blank\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 text-center\">\r\n");
      out.write("                    <div class=\"copyright_text   wow fadeInUp animated\">\r\n");
      out.write("                        <p>&copy; brandy 2015.All Right Reserved By <a href=\"http://www.themeforest.net/user/thecodecafe\"target=\"_blank\">Code Cafe Team</a></p>\r\n");
      out.write("                        <p>Made with love for creative people.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- =========================\r\n");
      out.write("     SCRIPTS \r\n");
      out.write("============================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/resources/include/dist2/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/include/dist2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/include/dist2/js/owl.carousel.js\"></script>\r\n");
      out.write("    <script src=\"/resources/include/dist2/js/wow.js\"></script>\r\n");
      out.write("    <script src=\"/resources/include/dist2/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fgetAsString_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:getAsString
    org.apache.tiles.jsp.taglib.GetAsStringTag _jspx_th_tiles_005fgetAsString_005f0 = new org.apache.tiles.jsp.taglib.GetAsStringTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005fgetAsString_005f0);
    try {
      _jspx_th_tiles_005fgetAsString_005f0.setJspContext(_jspx_page_context);
      // /resources/ContentLayout.jsp(12,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fgetAsString_005f0.setName("title");
      _jspx_th_tiles_005fgetAsString_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005fgetAsString_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
      // /resources/ContentLayout.jsp(57,14) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("header");
      _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    }
    return false;
  }
}
